Update paloalto.md
SEKOIA-IO/documentation pull request #105
Opened 2021-04-30 12:35 UTC by CharlesLR-sekoia

2021-04-30 21:18 UTC, otetard requested changes

2021-04-30 21:18 UTC, otetard commented on docs/integrations/paloalto.md
> +## I. Palo Alto logs
Title numbers are now automatically added in CSS, no longer needed to explicitly add them.

BTW, The full name of the company is “Palo Alto Networks”. I don’t know the full name of their product.

2021-04-30 21:18 UTC, otetard commented on docs/integrations/paloalto.md
> +## II. Transport to the concentrator
```suggestion
## II. Transport to the collector
```

2021-04-30 21:18 UTC, otetard commented on docs/integrations/paloalto.md
> +4) Click `Add` and enter the information that the firewall requires to connect to it:
```suggestion
1. In the GUI, go to `Device > Serve Profiles > Syslog`.
2. Click `Add` and enter a name for the profile such as `Syslog server`.
3. If the firewall has more than one virtual system (vsys), select the `Location` (vsys or `Shared`) where this profile is available.
4. Click `Add` and enter the information that the firewall requires to connect to it:
```

2021-04-30 21:18 UTC, otetard commented on docs/integrations/paloalto.md
> +6) Select both of the `Log at Session Start` and `Log At Session End` check boxes, and click `OK`.
```suggestion
1. Select `Objects > Log Forwarding`, click `Add`, and enter a `Name` to identify the profile.
2. For each log type (here Traffic, Threat and WileFire Malicious) and each severity level, select the `Syslog server` profile and click `OK`.
3. Select `Policies > Security` and select a policy rule.
4. Select the `Actions` tab and select the `Log Forwarding` profile you created.
5. In the `Profile Type` drop-down, select `Profiles` or `Groups`, and then select the security profiles or `Group Profiles` required to trigger log generation and forwarding.
6. Select both of the `Log at Session Start` and `Log At Session End` check boxes, and click `OK`.
```

2021-04-30 21:18 UTC, otetard commented on docs/integrations/paloalto.md
> +2) Click each Severity level (High and Critical if also fine), select the `Syslog server` profile, and click `OK`.
```suggestion
1. In the GUI, go to `Device > Log Settings`.
2. Click each Severity level (High and Critical if also fine), select the `Syslog server` profile, and click `OK`.
```

2021-05-03 07:46 UTC, celinequivy approved these changes

2021-05-04 07:36 UTC, celinequivy approved these changes

2021-05-04 08:35 UTC, merged