Update github_audit_logs.md
SEKOIA-IO/documentation pull request #1132
Opened 2023-06-22 10:12 UTC by GuillaumeCSekoia

2023-06-22 15:03 UTC, ka0ula commented on docs/xdr/features/collect/integrations/cloud_and_saas/github_audit_logs.md
> +**Note: according to [GitHub](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/audit-log) you must have GitHub enterprise and be Enterprise Admin to collect the Audit Logs.**
```suggestion
!!! Note
    According to [GitHub](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/audit-log), you must have GitHub enterprise and be Enterprise Admin to collect the Audit Logs.**
```

2023-06-27 09:23 UTC, Adamowoc requested changes

2023-06-27 09:23 UTC, Adamowoc commented on docs/xdr/features/collect/integrations/cloud_and_saas/github_audit_logs.md
> +    According to [GitHub](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/audit-log), you must have GitHub enterprise and be Enterprise Admin to collect the Audit Logs.
```suggestion
    You must be Administrator of the organization to create the audit logs API KEY.
```

We do not fetch the logs of a github enterprise but of a github organization :)

2023-06-27 09:34 UTC, Adamowoc approved these changes

2023-06-27 09:36 UTC, merged