feat(m365defender): rename the integration and add event types
SEKOIA-IO/documentation pull request #1176
Opened 2023-07-17 16:15 UTC by goudyj

2023-07-17 16:18 UTC, squioc requested changes

2023-07-17 16:18 UTC, squioc commented on docs/xdr/features/collect/integrations/cloud_and_saas/office365/microsoft_365_defender.md
> +* UrlClickEvents
UrlClickEvents is in public preview. So not implemented on our side.
```suggestion
```

2023-07-17 16:49 UTC, CharlesLR-sekoia approved these changes

2023-07-17 16:55 UTC, CharlesLR-sekoia approved these changes

2023-07-18 07:16 UTC, ka0ula approved these changes

2023-07-18 07:16 UTC, ka0ula commented on docs/xdr/features/collect/integrations/cloud_and_saas/office365/microsoft_365_defender.md
> +This setup guide describes how to forward events produced by `Microsoft 365 Defender` to SEKOIA.IO XDR.
```suggestion
This setup guide describes how to forward events produced by `Microsoft 365 Defender` to Sekoia.io XDR.
```

2023-07-18 07:16 UTC, ka0ula commented on docs/xdr/features/collect/integrations/cloud_and_saas/office365/microsoft_365_defender.md
> +Here is a list of all the Microsoft 365 Defender event types supported by this integration :
```suggestion
Here is a list of all the Microsoft 365 Defender event types supported by this integration:
```

2023-07-18 09:06 UTC, merged