Add the google reports drive documentation
SEKOIA-IO/documentation pull request #1266
Opened 2023-08-21 08:31 UTC by TOUFIKIzakarya

- Add Google Drive Reports Documentation

2023-08-21 15:10 UTC, Adamowoc requested changes

2023-08-21 15:10 UTC, Adamowoc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> +#### Prerequisites
```suggestion
### Prerequisites
```

2023-08-21 15:10 UTC, Adamowoc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> +#### Create a dedicated service account
```suggestion
### Create a dedicated service account
```

2023-08-21 15:10 UTC, Adamowoc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> +#### Create and download JSON keys (service account credentials)
```suggestion
### Create and download JSON keys (service account credentials)
```

2023-08-21 15:10 UTC, Adamowoc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> +#### Create your intake
```suggestion
### Create your intake
```

2023-08-21 15:10 UTC, Adamowoc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> +#### Pull the logs to collect them on Sekoia.io
```suggestion
### Pull the logs to collect them on Sekoia.io
```

2023-08-21 15:10 UTC, Adamowoc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> +#### Enjoy your events on the [Events page](https://app.sekoia.io/operations/events)
```suggestion
### Enjoy your events on the [Events page](https://app.sekoia.io/operations/events)
```

2023-09-05 13:04 UTC, squioc requested changes

2023-09-05 13:04 UTC, squioc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> + - Create the service account
Add another line between the previous sentence and the list for the layout
```suggestion

 - Create a project
 - Turn on the APIs for the service account
 - Set up the OAuth consent screen
 - Create the service account
```

2023-09-05 13:24 UTC, squioc requested changes

2023-09-05 13:24 UTC, squioc commented on docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md
> +1. Go to the [intake page](https://app.sekoia.io/operations/intakes) and create a new intake from the Google drive reports.
I forgot that I changed the name of the format
```suggestion
1. Go to the [intake page](https://app.sekoia.io/operations/intakes) and create a new intake from the `Google Report`.
```

2023-09-05 13:38 UTC, squioc approved these changes

2023-09-05 13:44 UTC, merged