Add docs for Microsoft IIS
SEKOIA-IO/documentation pull request #1481
Opened 2023-12-04 11:23 UTC by lvoloshyn-sekoia

2023-12-04 14:40 UTC, squioc requested changes
Thanks for the work.
Tabs are missing for notes and warnings that break the layout of the page. Can you fix it?

2023-12-04 14:40 UTC, squioc commented on docs/xdr/features/collect/integrations/application/microsoft_iis.md
> +While [Sekoia.io](http://sekoia.io/) docker concentrator is highly recommended, you are free to use the one that you are most comfortable with.
```suggestion
    While [Sekoia.io](http://sekoia.io/) docker concentrator is highly recommended, you are free to use the one that you are most comfortable with.
```

2023-12-04 14:40 UTC, squioc commented on docs/xdr/features/collect/integrations/application/microsoft_iis.md
> +In order to correctly represent these characters, it is recommended to install the [Sekoia.io agent](https://docs.sekoia.io/xdr/features/collect/integrations/endpoint/sekoiaio/). This endpoint agent
```suggestion
    The iso8859-1 character encoding is limited to 256 characters, which is not enough to represent all French characters. This means that some French characters might not be correctly interpreted or displayed when using iso8859-1 encoding. For example, iso8859-1 does not include characters such as é, è, ê, and ë.
    In order to correctly represent these characters, it is recommended to install the [Sekoia.io agent](https://docs.sekoia.io/xdr/features/collect/integrations/endpoint/sekoiaio/). This endpoint agent is specifically designed to handle such issues, ensuring the accurate and secure transmission of data.
```

2023-12-04 14:40 UTC, squioc commented on docs/xdr/features/collect/integrations/application/microsoft_iis.md
> +For more information, consult [NXLog documentation.](https://docs.nxlog.co/refman/current/xm/syslog.html)
```suggestion
    `OutputType Syslog_TLS` is needed for `TCP` transport even if you do not encrypt data. It does not depend on SSL transport at all.
    **Remove it ONLY** if you use `UDP` - `om_udp`.
    For more information, consult [NXLog documentation.](https://docs.nxlog.co/refman/current/xm/syslog.html)
```

2023-12-04 14:40 UTC, squioc commented on docs/xdr/features/collect/integrations/application/microsoft_iis.md
> +To ensure proper configuration, it is important to replace the `RSYSLOG_HOST` variable with the IP address of your concentrator.
```suggestion
    To ensure proper configuration, it is important to replace the `RSYSLOG_HOST` variable with the IP address of your concentrator.
```

2023-12-05 13:25 UTC, squioc requested changes
Two little changes to apply.

2023-12-05 13:49 UTC, lvoloshyn-sekoia commented on docs/xdr/features/collect/integrations/application/microsoft_iis.md
> +    **Remove it ONLY** if you use `UDP` - `om_udp`.
It seems to be connected, though: `Module om_udp` vs `Module om_tcp`. Perhaps, a mistake in the original doc?

2023-12-06 13:40 UTC, squioc approved these changes

2023-12-06 13:40 UTC, merged