add playbooks SPL format JSON Schema and doc for third-party playbook template contributors
SEKOIA-IO/documentation pull request #2054
Opened 2024-10-15 14:23 UTC by jeromefellus-sekoia

2024-10-16 13:45 UTC, squioc requested changes
LGTM. Just a little fix to apply in mkdocs.yml

2024-10-16 13:45 UTC, squioc commented on mkdocs.yml
> +# - intakes_by_uuid
This plugin must be preserved
```suggestion
 - intakes_by_uuid
```

2024-10-16 13:46 UTC, jeromefellus-sekoia commented on mkdocs.yml
> +# - intakes_by_uuid
outch nice catch thanks !

2024-11-08 08:08 UTC, pbivic approved these changes

2024-11-08 08:15 UTC, merged