Sophos EDR: documentation
SEKOIA-IO/documentation pull request #296
Opened 2022-05-24 17:58 UTC by squioc

add the documentation to ingest Sophos EDR events

2022-06-01 09:13 UTC, ka0ula commented on docs/operation_center/integration_catalog/endpoint/sophos_edr.md
> +Sophos EDR, monitor, detects and mitigates threats on endpoints.
```suggestion
Sophos EDR monitors, detects and mitigates threats on endpoints.
```

2022-07-29 12:25 UTC, PierrickV reviewed
Thank you for this work ! :+1: 

:warning:  You have an auto-generated file into this PR

2022-07-29 12:25 UTC, PierrickV commented on docs/operation_center/integration_catalog/endpoint/sophos_edr.md
> +This setup guide shows how to forward events produced by Sophos EDR to SEKOIA.IO.
```suggestion
This setup guide describe how to forward events produced by Sophos EDR to SEKOIA.IO.
```

2022-07-29 12:25 UTC, PierrickV commented on docs/operation_center/integration_catalog/endpoint/sophos_edr.md
> +In the Sophos Central Admin, go to `Global Settings > API Credentials Management`.
```suggestion
In the Sophos Central Admin console, go to `Global Settings > API Credentials Management`.
```

2022-07-29 12:25 UTC, PierrickV commented on docs/operation_center/integration_catalog/endpoint/sophos_edr.md
> +Create a new token with `Add Credential`. Type a Credential name, select the appropriate role and add a description.
```suggestion
Create a new token with `Add Credential`. Complete the name, appropriate role and description.
```

2022-07-29 12:25 UTC, PierrickV commented on docs/operation_center/integration_catalog/endpoint/sophos_edr.md
> +Get the [Sophos Central SIEM integration script](https://github.com/sophos/Sophos-Central-SIEM-Integration). Configure it according [this guide](https://support.sophos.com/support/s/article/KB-000036
```suggestion
Get the [Sophos Central SIEM integration script](https://github.com/sophos/Sophos-Central-SIEM-Integration) and configure it by following [this Sophos guide](https://support.sophos.com/support/s/article/KB-000036372?language=en_US).
```

2022-07-29 12:25 UTC, PierrickV commented on docs/operation_center/integration_catalog/endpoint/sophos_edr.md
> +See our [Ingestion methods page](https://docs.sekoia.io/operation_center/data_collection/ingestion_methods/) to select the appropriate methods to forward your events to sekoia.io according to your ne
```suggestion
See the [Ingestion methods page](https://docs.sekoia.io/operation_center/data_collection/ingestion_methods/) to select the appropriate method to forward your events to SEKOIA.IO according to your needs.
```

> Don’t use "I", "our", "us", "we", use "you".

https://zeroheight.com/6104b1d12/p/859e67-pronouns

> When referring to SEKOIA.IO, always put the name in capital letters. 

https://zeroheight.com/6104b1d12/p/9392ba-capitalization

2022-08-18 13:40 UTC, gaelmuller requested changes

2022-08-18 13:40 UTC, gaelmuller commented on docs/xdr/features/collect/integrations/endpoint/sophos_edr.md
> +Go to the [intake page](https://app.sekoia.io/operations/intakes) and create a new intake from the format `AWS CloudTrail`.
```suggestion
Go to the [intake page](https://app.sekoia.io/operations/intakes) and create a new intake from the format `Sophos EDR`.
```

2022-08-18 13:48 UTC, gaelmuller approved these changes

2022-08-18 13:48 UTC, merged