feat(documentation): Add Cloudflare and update auto-generated documentation.
SEKOIA-IO/documentation pull request #298
Opened 2022-05-25 09:38 UTC by PierrickV

2022-05-25 09:47 UTC, squioc requested changes
Auto-generated file were embedded in the PR. I think they should be pushed in another PR.
Please update mkdocs.yml to point to your documentation, otherwise the user will be unable to access it

2022-06-03 10:35 UTC, squioc requested changes
Some suggestions and a missing redirect

2022-06-03 10:35 UTC, squioc commented on docs/operation_center/integration_catalog/cloud_and_saas/cloudflare/cloudflare_logpull.md
> +
```suggestion

### Create the intake

Go to the [intake page](https://app.sekoia.io/operations/intakes) and create a new intake from the format Cloudflare.

# Pull the events
```

2022-06-03 10:35 UTC, squioc commented on docs/operation_center/integration_catalog/cloud_and_saas/cloudflare/cloudflare_logpull.md
> +To start your playbook with a template, go to: "Create a new playbook" > "Use a template" > Search for Cloudflare.
```suggestion
To pull events, go to [the playbook page](https://app.sekoia.io/operations/playbooks) and create your playbook with a template: "Create a new playbook" > "Use a template" > Search for Cloudflare.
```

2022-06-03 10:35 UTC, squioc commented on mkdocs.yml
> +      - Cloudflare:
Could you also add the following entry:
```
      integrations/cloudflare.md: operation_center/integration_catalog/cloud_and_saas/cloudflare/cloudflare_logpull.md
```
in the section `plugins > redirects > redirect_maps`.
Thanks

2022-06-07 09:55 UTC, squioc submitted a review, later dismissed

2022-06-07 12:09 UTC, ka0ula commented on docs/operation_center/integration_catalog/cloud_and_saas/cloudflare/cloudflare_logpull.md
> +In this documentation we will explain how to collect and send Cloudflare HTTP logs to SEKOIA.IO.
```suggestion
In this documentation, you will learn how to collect and send Cloudflare HTTP logs to SEKOIA.IO.
```

2022-06-08 08:48 UTC, squioc approved these changes

2022-06-08 08:48 UTC, merged