Release Notes: 2020-12-17 notes (Operation Center dashboards)
SEKOIA-IO/documentation pull request #32
Opened 2020-12-15 17:06 UTC by otetard

![image](https://user-images.githubusercontent.com/2007634/103745620-13f55780-5000-11eb-8a87-683d4168ead9.png)

2020-12-15 17:49 UTC, r1chev approved these changes

2021-01-05 23:25 UTC, gbossert requested changes

2021-01-05 23:25 UTC, gbossert commented on docs/releases/2020-12-17.md
> +Dashboard are composed of modular widgets that can be placed where you want. Widgets can be configured to specify the date range, applied filters, display, etc.
```suggestion
Dashboards are composed of modular widgets that can be placed where you want. Widgets can be configured to specify the date range, applied filters, display, etc.
```

2021-01-05 23:25 UTC, gbossert commented on docs/releases/2020-12-17.md
> +SEKOIA.IO comes with a pre-configured dashboard that gives a synthetic view of the current community activity, either from a operationnal security perspective (risk level, number of alerts, etc.) and
```suggestion
SEKOIA.IO comes with a pre-configured dashboard that gives a synthetic view of the current community activity, either from an operational security perspective (risk level, number of alerts, etc.) or from an activity perspective (list of last posted comments, last created alerts, etc.).
```

2021-01-05 23:25 UTC, gbossert commented on docs/releases/2020-12-17.md
> +All SEKOIA.IO users are able to create new dashboard that would fit their specific needs. It’s also possible to clone an existing dashboard.
```suggestion
All SEKOIA.IO users are able to create new dashboards that fit their specific needs. It’s also possible to clone an existing dashboard.
```

2021-01-05 23:25 UTC, gbossert commented on docs/releases/2020-12-17.md
> +SEKOIA.IO’s Operation Center provides a several widgets:
```suggestion
SEKOIA.IO’s Operation Center provides several widgets:
```

2021-01-06 08:17 UTC, otetard commented
Thanks @gbossert for the review and suggestions. I’ve applied you changes and update the date in the notes. I’ve also updated all images to remove all gray borders.

2021-01-06 08:21 UTC, gbossert approved these changes

2021-01-06 08:46 UTC, merged