Enhance rsyslog documentation
SEKOIA-IO/documentation pull request #594
Opened 2022-10-20 11:39 UTC by ka0ula

- Remove the huge titles
- Improve english

2022-10-20 13:55 UTC, squioc requested changes

2022-10-20 13:55 UTC, squioc commented on docs/xdr/features/collect/ingestion_methods/rsyslog.md
>  # *.* /var/log/testing.log;SEKOIAIOTesting
Due to the indentation, this block is not well rendered

2022-10-21 08:58 UTC, squioc requested changes

2022-10-21 08:58 UTC, squioc commented on docs/xdr/features/collect/ingestion_methods/rsyslog.md
> +		Use `ip addr` command to find the relevant information to relace `<change_with_interface_name>`.
```suggestion
		Use `ip addr` command to find the relevant information to replace `<change_with_interface_name>`.

```

2022-10-21 09:53 UTC, squioc approved these changes
Nice work :+1:!!

2022-10-21 09:57 UTC, ka0ula commented
@squioc thanks for the review! I hope it helps 😊

2022-10-21 09:57 UTC, merged