Add "Configure a notification to report on inactive intake"
SEKOIA-IO/documentation pull request #658
Opened 2022-11-22 13:16 UTC by ValClaf

2022-11-24 13:43 UTC, ValClaf commented
@ka0ula may you just review the PR bot not merge it. We need to wait for the next deployment in production to merge it. The next deployment is planned for Tuesday (2022_11_29).

2022-11-24 14:21 UTC, ka0ula requested changes

2022-11-24 14:21 UTC, ka0ula commented on docs/xdr/features/collect/intakes.md
> +3. Choose how you want to be notified. Triggers action available are mentioned is this page [Turn on notifications](notifications.md). You can also set up your notification from the user center>notif
```suggestion
3. Select how you want to be notified. Triggered actions that are available are mentioned in the page [Turn on notifications](/getting_started/notifications/#triggered-actions.md). 

!!! note
     You can also set up this notification from the User Center > Notifications by selecting the trigger `No events are received`. 
```

2022-11-29 10:39 UTC, ka0ula approved these changes

2022-11-29 10:40 UTC, merged