Add documentation for AIX and Intune parser
SEKOIA-IO/documentation pull request #663
Opened 2022-11-24 13:30 UTC by Thibault-MAL

Please find my latest contribution to the wonderful docs.sekoia.io

2022-11-24 13:34 UTC, CharlesLR-sekoia approved these changes

2022-11-24 13:53 UTC, squioc requested changes

2022-11-24 13:53 UTC, squioc commented on docs/xdr/features/collect/integrations/endpoint/ibm_aix.md
> +Log on your NIOS appliance and follow [this guide](https://www.ibm.com/docs/en/dsm?topic=aado-configuring-aix-audit-dsm-send-syslog-events-qradar) to enable syslog forwarding
NIOS is another technology. I suggest deleting this part of the sentence.
```suggestion
Follow [this guide](https://www.ibm.com/docs/en/dsm?topic=aado-configuring-aix-audit-dsm-send-syslog-events-qradar) to enable syslog forwarding for audit events
```

2022-11-24 13:53 UTC, squioc commented on docs/xdr/features/collect/integrations/endpoint/microsoft_intune.md
> +Configure Azure Front door to stream its logs to the EventHub with [this guide](https://docs.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-logs#configure-logs).
```suggestion
Configure Microsoft Intune door to stream its logs to the EventHub with [this guide](https://learn.microsoft.com/en-us/mem/intune/fundamentals/review-logs-using-azure-monitor).
```

2022-11-24 13:56 UTC, squioc requested changes

2022-11-24 13:56 UTC, squioc commented on docs/xdr/features/collect/integrations/endpoint/ibm_aix.md
> +
Recent change on the documentation, to associate rule to datasource, we should include a new autogenerated document
```suggestion
{!_shared_content/operations_center/detection/generated/suggested_rules_e8cb3372-41c8-409f-8e0e-ca4e6cecf7e6_do_not_edit_manually.md!}

```

2022-11-24 13:56 UTC, squioc commented on docs/xdr/features/collect/integrations/endpoint/microsoft_intune.md
> +
Recent change on the documentation, to associate rule to datasource, we should include a new autogenerated document
```suggestion
{!_shared_content/operations_center/detection/generated/suggested_rules_c20528c1-621e-4959-83ba-652eca2e8ed0_do_not_edit_manually.md!}

```

2022-11-24 13:59 UTC, squioc commented
My bad. Could you add these two new documentations in the mkdocs.yml (in order to display them in the menu)?

2022-11-24 14:25 UTC, ka0ula requested changes

2022-11-24 14:25 UTC, ka0ula commented on docs/xdr/features/collect/integrations/endpoint/ibm_aix.md
> +## Transport to SEKOIA.IO
```suggestion
## Send logs to SEKOIA.IO
```

2022-11-28 08:42 UTC, ka0ula commented on docs/xdr/features/collect/integrations/endpoint/microsoft_intune.md
> +Then go to `Security + networking > Access keys` and copy the key1 `Connection string`
```suggestion
Then go to `Security + networking > Access keys` and copy the key1 `Connection string`.
```

2022-11-28 09:08 UTC, merged