doc(SSO): Document configuration on identity provider side
SEKOIA-IO/documentation pull request #840
Opened 2023-02-03 15:14 UTC by PierrickV

2023-02-06 09:58 UTC, otetard commented on docs/getting_started/sso/okta.md
> +Once your app as been created:
```suggestion
Once your app has been created:
```

2023-02-06 09:58 UTC, otetard commented on docs/getting_started/sso/okta.md
> +4. In `Assignments` > `Controlled access`, you can limit access to certain group of users
```suggestion
4. In `Assignments` > `Controlled access`, you can limit access to specific groups of users
```

2023-02-06 09:58 UTC, otetard commented on docs/getting_started/sso/okta.md
> +Okta can be configured to restrict which user are allowed to access SEKOIA.IO.
```suggestion
Okta can be configured to restrict which users are allowed to access SEKOIA.IO.
```

2023-02-08 14:05 UTC, ka0ula requested changes

2023-02-08 14:05 UTC, ka0ula commented on docs/getting_started/sso/okta.md
> +1. Save the `Client ID` & `Client secret` for latter use
```suggestion
1. Save the `Client ID` & `Client secret` for further use
```

2023-02-08 14:05 UTC, ka0ula commented on docs/getting_started/sso/azure.md
> +You are ready to configure input your configuration to SEKOIA.IO
```suggestion
You are ready to input your configuration to SEKOIA.IO
```

2023-02-08 14:05 UTC, ka0ula commented on docs/getting_started/sso/okta.md
> +2. In `Assignments` > `Assign` you can select `Assign to People` or `Assign to Groups`
```suggestion
2. In `Assignments` > `Assign`, you can select `Assign to People` or `Assign to Groups`
```

2023-02-08 14:09 UTC, ka0ula commented on docs/getting_started/sso/azure.md
> +1. On the main page, save the `Application (client) ID` for latter use
```suggestion
1. On the main page, save the `Application (client) ID` for further use
```

2023-04-03 13:03 UTC, closed without merging