Update/quickstart api
SEKOIA-IO/documentation pull request #900
Opened 2023-02-23 11:49 UTC by goudyj

* Add an API quickstart, explaining how to use our API with examples.
* Remove the old `Overview` section which has no added value in my opinion.

2023-02-23 12:44 UTC, Men-hau requested changes

2023-02-23 12:44 UTC, Men-hau commented on docs/xdr/develop/quickstart.md
> +Python is a langage that can be used to interact with the SEKOIA.IO API. Please find below two examples, one with a `GET` request with `query parameters` and another with a `POST` request and an `app
```suggestion
Python is a language that can be used to interact with the SEKOIA.IO API. Please find below two examples, one with a `GET` request with `query parameters` and another with a `POST` request and an `application/json` body.

```

2023-04-20 14:07 UTC, Men-hau approved these changes

2023-04-21 16:04 UTC, CharlesLR-sekoia approved these changes

2023-04-24 07:28 UTC, merged